---
title: "tb_tidy"
output: html_document
author: John H Reeves
date: 2021-08-29
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# loads tidyverse then readsRDS
library(tidyverse)
tb <- readRDS("tb_tidy.rds")
tb
```
```{r}
tb_au <- filter(tb,
                country =="Australia",
                !is.na(age_group))
tb_au
```



```{r}
library(ggplot2)
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity", position = "fill") +
  facet_grid(~ age_group) +
  scale_fill_brewer(palette="Dark2")
p
```
```{r}
library(ggplot2)
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(~ age_group) +
  scale_fill_brewer(palette="Dark2")
p
```

```{r}
library(ggplot2)
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(~ age_group) +
  scale_fill_brewer(palette="Dark2")
p
```
```{r}
library(ggplot2)
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity") +
  facet_grid(sex ~ age_group) +
  scale_fill_brewer(palette="Dark2")
p
```


```{r}
library(ggplot2)
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity") +
  facet_grid(~ sex) +
  scale_fill_brewer(palette="Dark2")
p
```

```{r}
rainbow <- ggplot(tb_au, aes(x = 1, y = count, fill = factor(year))) +
  geom_bar(stat = "identity", position="fill") +
  facet_grid(sex ~ age_group) 
rainbow
```
```{r}
p <- ggplot(tb_au, aes(x = year, y = count, fill = sex)) +
  geom_bar(stat = "identity") +
  facet_grid(sex ~ age_group) +
  scale_fill_brewer(palette="Dark2") + 
  coord_polar() 
p
```
```{r}
rainbow +
  coord_polar(theta = "y")
```

